export const API_ERROR = 'EVENT/API_ERROR_RECEIVED'
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED'

export const METRICS_DATA_RECEIVED = 'METRICS_DATA_RECEIVED'

export const FETCH_30_MINUTES_DATA = 'FETCH_30_MINUTES_DATA'
export const MULIPLE_METRICS_RECEIVED = 'MULIPLE_METRICS_RECEIVED'

export const START_LIVE_UPDATES = 'START_LIVE_UPDATES'